pages:
      name: "CovidCashAid \nEnter your Firstname and Lastname E.g Hassan Okoye: "
      address: "CovidCashAid \nEnter your full address (Lockdown areas only): "
      account_no: "CovidCashAid \nEnter your Account Number: "
      bank_name: "CovidCashAid \nEnter your Bank Name: "
      lga: "CovidCashAid \nEnter LGA: "
      state: "CovidCashAid \nEnter State: "
      bvn: "CovidCashAid \nEnter your BVN Number: "
      gender: "CovidCashAid \nSelect Gender: \n1. Male \n2.Female "
      dob: "CovidCashAid \nEnter Date of Birth E.g 19/08/1960 "
      thank_you: "CovidCashAid \nThank you! Your application has been recieved "
      menu: "Welcome to CovidCashAid \nDo you have an account? \n1. Yes \n2. No "
