pages:
  welcome: "Welcome to Baxi Mobile USSD Services: \n1. Register\n2.Transfer Funds\n3. Fund Wallet\n4. Check Balance"
  new_user: "New User registration.\nEnter username(one word no spaces,eg:johndoe) :\n00. Back"
#   amount_to_wallet: "Enter Amount to Fund into Wallet:"
#   banks: "Select bank: \n1. ACCESS \n2. ECOBANK\n3. FBN\n4. FIDELITY\n5. GTB \n6. KEYSTONE \n7. STANBIC IBTC PLC \n8. STERLING \n9. UBA \n10. UNITY \n11. WEMA \n12. ZENITH"
  amount_transfer: "Enter Amount to Transfer from Wallet:"
  amount_fund: "Enter Amount to Fund Wallet:"
  balance: "Wallet Balance Enquiry.\nEnter your 4-digit PIN to confirm:"
#   add_bank: "Select a bank: \n1. ZENITH BANK\n2. GTB\n3. UBA\n4. STANBIC IBTC PLC\n5. STERLING BANK PLC\n6. UNITY BANK\n7. KEYSTONE BANK\n8. FIDELITY BANK\n9. ECO BANK\n10. WEMA BANK\n11. ACCESS BANK\n12. FIRST BANK"
  pin: "Enter 10-digit NUBAN Account Number:"
  ask_pin: "Enter your 4-digit PIN:"
  success: "Transaction Successful"
  account: "Enter 10-digit NUBAN Account Number:"
  trans_success: "Funds Transfer\nTransaction Successful"
  bank_one: "1. ACCESS\n2. ACCESS(DIAMOND)\n3. ACCION MFB\n4.  CITIBANK\n5. ECOBANK\n6. ENTERPRISE\n7. FCMB\n8. FIDELITY\n9.FIRST BANK\n0. MORE"
  bank_two: "1. GTB\n2. HERITAGE\n3. JAIZ\n4. KEYSTONE\n5. KUDA MFB\n6. PAGA\n7. POLARIS\n8. PRESTIGE\n9. PROVIDUS\n0. MORE"
  bank_three: "1. SAFETRUST\n2. STANBIC IBTC\n3. STANDARD CHARTERED\n4. STERLING\n5. SUNTRUST\n6. TAJ BANK\n7. TITAN TRUST\n8. TAGPAY\n9. TEASY MOBILE\n0. MORE"
  bank_four: "1. UNIBEN MFB\n2. UNICAL MFB\n3. UNION\n4. UBA\n5. UNITY\n6. VFD MFB\n7. WEMA\\n8. ZENITH"
       
