pages:
      thank_you: "Welcone to RCCG Mobile World \nThank you! Your Donation has been recieved "
      menu: "Welcome to RCCG MOBILE WORLD \nSelect: \n1. National \n2. Parish \nJesus Christ the same yesterday, today and forever. Hebrew 13:8"
      banks: "Select bank: \n1. ACCESS \n2. ECOBANK\n3. FBN\n4. FCMB \n5. FIDELITY\n6. GTB \n7. Heritage\n8. KEYSTONE \n9. STANBIC IBTC PLC \n10. STERLING \n11. UBA \n12. UNITY \n13. VFD\n14. WEMA \n15. ZENITH"
      collection_type: "IN RCCG WE'VE FOCUSED ON THE SPREAD OF THE GOSPEL. TO SUPPORT KINDLY SELECT: \n1. PARTNER75 \n2. TITHE\n3. THANKSGIVING \n4. OFFERING \n5. FIRSTFRUIT \n6. NEW AUDITORIUM"
      amount: "It is more blessed to give - Acts 20:35b \nWelcome to RCCG Mobile \nPlease enter the amount you want to give: "
      parish_code: "Welcome to RCCG \nEnter your parish code: "
      coming_soon: "Welcome to RCCG Mobile world \nThis menu is comming soon. \nPress 1 to switch to National. "
