pages:
    # main_menu: "LAPO Swift Banking:\n1. Airtime\n2. Transfer\n3. Paybills\n4. Check Balance\n5. Airtime to Deposit\n6. Data\n7. Mini Statement\n8. Loan\n9. Self Service"
    main_menu: "LAPO Swift Banking:\n1. Airtime\n2. Transfer\n3. Pay Bills\n4. Check Balance\n5. Data\n6. Mini Statement\n7. Self Service\n8. Loan"
    new_ussd_customer: "Welcome To LAPO Swift Banking\n1. Create Pin"
    bank_one: "Select Bank\n1. Access\n2. Citibank\n3. Diamond Access\n4. Ecobank\n5. Enterprise\n6. Fidelity\n7. FBN\n8. FCMB\n00. Back"
    bank_two: "Select Bank\n1.GTB\n2. Heritage\n3. Jaiz\n4. Keystone\n5. Mainstreet Bank\n6. PRESTIGE MFB\n7. Providus\n00. Back"
    bank_three: "Select Bank\n1.SAFETRUST\n2. Stanbic IBTC\n3. Standard Chartered\n4. Sterling\n5. Suntrust\n6. Union Bank\n7. UBA\n8. Unity Bank\n00. Back"
    bank_four: "Select Bank\n1. Wema\n2. Zenith\n00. Back"
    open_an_account: "Welcome to LAPO Swift Banking\nYou are about to open an INDIVIDUAL SAVINGS ACCOUNT:\n\nEnter your BVN:"

    enter_bvn_lapo: "Enter Your BVN:"
    
    other_name: "Enter other names:"
    gender: "Select gender:\n1. Male\n2. Female\n00. Back"
    state_of_residence: "Enter your state of residence:"
    success: "Your LAPO savings account has been created successfully:"
    enter_date_birth: "Enter you date of birth (yyyy-mm-dd).\nfor example. 3rd July, 2002\n Enter 2002-07-03:"



    # steps for menu 2. Airtime Purchase
    airtime_for: "1. Airtime(Self)\n2. Airtime(Other)\n00. Back"
    airtime: "Enter Amount:"
    debit_account:  "Enter Debit Account Number"
    aritime_others: "Enter Mobile Number:"



    # steps for menu 4. Data
    data_for: "1. Data(Self)\n2. Data(Other)\n00. Back"



    # steps for menu 3. Pay Bills
    billers: "Select:\n1. Sports & Gaming\n2. Utilities\n3. Distributor Payments\n00. Back"
    sport: "Select Biller:\n1. Bet9Ja\n2. Naira Bet\n3. Naija Bet\n4. Betway\n5. Black Bet\n00. Back"
    utilities: "Select Biller:\n1. IKEDC\n2. EKEDC\n3. Ibadan\n4. Kaduna\n5. Kano\n6. LCC\n7. Port Harcourt\n00. Back"

    distributor: "Select Biller:\n1. DSTV\n2. GOTV\n3. Smile\n4. Star Times\n5. Swift\n00. Back"

    dstv: "Select product\n1. Asian Add-on\n2. Asia\n3. Compact\n4. Compact+Asia\n5. Compact+Asia+Xtraview\n6. Compact+French Plus\n00. Back"

    dstv_code: "Enter your DSTV Smart Card Number:"
    lcc: ""
    electricity: ""
    internet_service: ""
    cus_number: "Enter Customer Number:"



    
    # steps for menu 4. Transfer Funds
    transfer_type: "Select Destination Bank\n1. LAPO - LAPO\n2. Other banks\n00. Back"
    debit_account: "Enter Debit Account Number:"
    credit_account: "Enter Account Number:"
    tranfer_amount: "Enter Amount:"
    recepient: "Enter Recipient's Account Number:"
    beneficiary_number: "Enter Beneficiary Phone Number"


    # steps for menu 5. Airtime to Account Deposit
    airtime_account: "Select Destination Bank\n1. My LAPO Account\n2. Other Bank\n00. Back"
    #/// steps for destination 1. My LAPO account
    airtime_type: "Select mode of Transfer\n1. Airtime Voucher\n2. Airtime Balance\n00. Back"
    #/// steps for account Airtime Voucher
    vendor_voucher: "Select Network Provider\n1. MTN\n2. GLO\n3. Airtel\n4. 9Mobile\n00. Back"
    #/// steps for account Airtime Balance



    # steps for menu 6. Check Account Balance
    account_number: "Enter Account Number:"
    check_balance: "Enter 4-digit PIN"


    # steps for menu 7. Self Service
    self_sev: "Select service:\n1. Create new account for existing customer:\n2. Reset PIN:\n3. Block Debit\n4. Forgot PIN\n00. Back"
    forgot: "LAPO Swift Banking:\nContact our Customer Care Representative\nOn +234 8139 840 230 to retrive your PIN\n00. Back"
    oldpin: "Enter Current 4-digit PIN"
    new_pin: "Enter New 4-digit PIN"
    


    # steps for menu 8. Mini Statement
    mini_statement: "Enter 4-digit PIN"
    # statement: "Select statement:\n1. Check account numbers:\n2. Check account details "
     
    invalid_code: "Connection problem or invalid MMI code."


    # steps for menu 9. Request for loan

    flexcube_down: "LAPO Swift Banking\nService temporarily unavailable please try again later."



    ####################################################################################### PCASH ######################################################################################
   
    pcash_menu: "pCash Nano Lending:\n1. LOAN\n2. My pCash Account Balance\n3. Transfer\n4. Data\n5. Airtime\n6. Pay Bills\n7. Self Service"
    welcome: "Welcome To pCash Nano Lending:\n1. Create Account"
    loan_menu: "pCash Nano Lending:\n1. Apply for Loan\n2. Check Loan Balance\n3. Repay Loan"
    p_success: "Your pCash Nano Lending account has been created successfully:"
    account_type: "Select Beneficiary:\n1. Self account\n2. 3rd party account"
    principal: "Enter Amount"
    beneficiary_account: "Enter Account Number"
    self_service: "Select a service\n1. Loan Eligibility Status\n2. Pin Reset\n3. Loan Limit\n4. Forgot PIN"
    enter_bvn: "You are about to open a\npCash Nano Lending account\n\nEnter your BVN:"
    invalid: "Enter a valid BVN number"
    enter_first_name: "Enter  first name:"
    enter_last_name: "Enter last name:"
    enter_pin: "Enter Prefered 4 digit pin:"
    pin: "Enter Your 4-digit PIN"
    error: "an error occured\n Please try again"
    banking: "Select bank: \n1. ACCESS\n2. ECOBANK\n3. FBN\n4. FCMB\n5. FIDELITY\n6. GTB\n7. Heritage\n8. KEYSTONE\n9. STANBIC\n10. STERLING\n11. UBA\n12. UNION\n13. VFD\n14. WEMA\n15. ZENITH"
    not_customer: "pCash Nano Lending:\nPhone number not registered on pCash\nDial *371*8# to register"
    p_forgot: "pCash Nano Lending:\nContact Our Customer Care Representative\nOn (+234) 813 984 0230 to retrieve your PIN"
    tenure_day: "Select Loan Tenure\n1. 10 Days (7% int.rate)\n2. 15 Days (10% int. rate)\n3. 20 Days (13% int. rate)\n4. 30 Days (15% int. rate)."
    card:  "Enter Card Number:"
    cvv: "Enter Card CVV:"
    exp_expiry: "Enter Expiry Date:"
    banks: "Select Bank Number\n\n1. A - F\n2. G - P\n3. S - U \n4. V - Z"
    pbank_one: "Select Bank\n1. Access\n2. Citibank\n3. Diamond Access\n4. Ecobank\n5. Enterprise\n6. Fidelity\n7. FBN\n8. FCMB\n0. Back"
    pbank_two: "Select Bank\n1.GTB\n2. Heritage\n3. Jaiz\n4. Keystone\n5. Mainstreet Bank\n6. Parallex Bank\n7. Providus\n0. Back"
    pbank_three: "Select Bank\n1.Skye Bank\n2. Stanbic IBTC\n3. Standard Chartered\n4. Sterling\n5. Suntrust\n6. Union Bank\n7. UBA\n8. Unity Bank\n0. Back"
    pbank_four: "Select Bank\n1. Wema\n2. Zenith\n0. Back"  
    not_a_customer: "pCash Nano Lending:\nPhone number not registered on pCash"
    open_pcash_account: "You are about to open a pCash account:\n1. Open with BVN\n2. Open without BVN"
