pages:
    welcome: "Universal Insurance Plc 3rd Party:\n1. Buy Policy\n2. Renew Existing Policy\n3. Check Policy Status"
    new: "New Motor 3rd Party Insurance\n Enter Owner Name(Eg: MUSA EZE AYO)"
    enter_vehicle_plate_number: "Enter Vehicle Plate Number(Eg: krd823bm)"
    enter_reg_chasis: "Enter Your Vehicle Chassis Number(Eg: 2H2XA59BWDY98766)"
    enter_vehicle_make: "Enter Your Vehicle Make(Eg: Honda)"
    enter_vehicle_color: "Enter Your Vehicle Color(Eg: Black)"
    enter_vehicle_model: "Enter Your Vehicle Model(Eg: Civic)"
    enter_vehicle_year: "Enter Your Vehicle Year(Eg: 2010)"
    enter_email: "Enter Your Email(Eg: example(at)gmail.com)"
    APIKEY: "KG69034WRVFPL987ZB"
    Username: "USSD_2108"
    Password: "LG34YXG57"
    renewal: "Universal Insurance Plc\nVehicle 3rd Party Renewal\nEnter vehicle plate number (Eg: krd823bm)"
    activate: "Universal Insurance Plc\nVehicle 3rd Party Activation\nEnter Vehicle Chasis Number(Eg:xx1331134 )"
    status: "Policy Number:"
    policy_num: "Policy Number:"
    reg_num: "Registration NO:"
    exp_date: "Expiration Date:"
    policy_status: "Policy Status:"
    mcash_note: "Press 1 To Continue Payment"
    active: "Your policy is still active"
    message: "You have not registerd this plate number for a new policy. \n Dial *20065# to get started."
    null_message: "Message"
    amount: "Enter amount"
    account_number: "Enter account Number:"
    user_name: "Enter Fullname (eg:MUSA EZE AYO): "
    pin_num: "Enter PIN generated from hardware token:"
    dob: "Enter date of birth(DDMMYYYY) Required by your bank:"
    bvn: "Enter BVN number:"
    otp: "Please Enter the OTP sent to your phone number(OTP expires in 3 minutes)"
    error: "Thank you for using this service"
    add_bank: "Select a bank: \n1. ZENITH\n2. GTB\n3. UBA\n4. STANBIC IBTC\n5. STERLING\n6. UNITY\n7. KEYSTONE\n8. FIDELITY\n9. ECO BANK\n10. WEMA\n11. ACCESS\n12. FBN"
    authorize: "Please Enter You OTP"
    empty_account: "You do not have any bank account registed with us"
    invalid_entry: "Invalid Entry\n Thank you for using this service"
    delete_message: "Deleted successfully"
    valid_name: "Enter a valid name"
    dail_stack: "Dear Subscriber, \nDial *372*1*64# to complete your payment"
    dail_rave:  "Dear Subscriber, \nDial *372*1*65# to complete your payment"
   
