pages:
    welcome: "MAGPORA Services: \n1. Book Visitor \n2. Get Visitor's Record\n3. Cancel Visitor"
    name: "MAGPORA Services: \nEnter Your Name: "
    number: "MAGPORA Services: \nEnter Visitor's Phone Number "
    phone: "MAGPORA Services: \nEnter Your Phone number: "
    destination: "MAGPORA Services: \nEnter Your Address: "
    email: "MAGPORA Services: \nEnter Your Email: "
    compliant: "Select category type: \n1. Electricity\n2. Water\n3. Security\n4. Infrastructure\n5. Others"
    complianttype: "MAGPORA Complaint: \nEnter your complaint:"
    summary: "MAGPORA Account Summary: \nProperty: House 116 \nTotal paid: 125,000 \nOutstanding: 15,000"
    message: "MAGPORA Complaint: \nThank you your complaint has been \nreceived and repoerted to the \nrelevant department"
    select_bank: "Select a bank: \n1. ACCESS BANK NIGERIA\n2. STERLING BANK PLC\n3. PROVIDUS BANK\n4. UNITY BANK PLC\n5. ZENITH BANK PLC\n6. GTB\n7. OTHER BANKS"
    cancel: "Visitor Booking Cancelled. \nThank You"
    not_registered: "This Number is not \nregistered to a visitor. Dial *372*10# to Get Started"
    purpose: "MAGPORA Services: \nEnter Purpose of Visit"
    not_found: "Mobile Number Not Regestered \nContact Magpora Admin \nadmin@magpora.com"


