pages:
    back : "\n0. Go Back"
    intro: "It pays to pay your tax!\nPress 1 to continue"
    welcome : "Ondo State Internal Revenue Service. \n1. Register \n2. Last Payment \n3. Pay Tax\n4. Tax Calculator\n5. Check TaxPayer"
    enter_tin : "Enter your OIRS PayerID or Mobile number"
    self_others: "Account type \n1. Self\n2. Another\n"
    enter_mobile: "Enter mobile number(E.g 08012345678):"
    enter_email: "Enter email"
    confirm_registration : "New Taxpayer\n"
    confirm_payment : "Individual payment\nPress 1 to confirm"
    payment_amount : "Enter Amount:"
    self_assessment : "Self-Assessment"
    cancel : "Request not confirmed & cancelled"
    new_payer : "Redirecting to mCash for Payment.."
    do_payment : "Redirecting to mCash for Payment.."
    unknown : "Your request was not understood"
    payment_summary: "Pay Self-Assessment\n"
    mcash_note: "Press 1 to complete payment"
    payer_id: "PayerID: "
    amount: "Amount: "
    calculator_options: "Tax Calculator\n1. Self-Assessment\n2. P.A.Y.E"
    monthly_income : "Enter Monthly Income:"
    monthly_basic : "Enter Annual Basic Salary:"
    lbl_min_tax_rate: "Minimum Tax Rate: "
    lbl_min_tax: "Minumum Tax Payable: "
    lbl_monthly_income: "Monthly Income: "
    input_nhf_rate: "N.H.F (%): "
    input_pension_rate: "Pension (%): "
    PAYE: "P.A.Y.E"
    registration_failed: "Unable to register new TaxPayer now\nPlease try again later"
    confirm: "Press 1 to confirm your request"
    taxinfo : "Tax Info provides latest updates, news and info about tax-related matters. Service costs N10/week\nPress 1 to subscribe"
    taxinfo_2: "You have subscribed to TaxInfo. You will receive latest updates, news and info about tax-related matters weekly"
    tax_payment_options: "Pay\n1. Witholding Tax (Individual)\n2. Business Premises\n3. Development Levy\n4. Market Tax\n5. P.A.Y.E\n6. Land Use"
    witholding_tax_options: "Pay Witholding Tax (Individual)\n1. Rent\n2. Professional Services\n3. Contract\n4. Directors Fees"
    business_premises_options: "Pay Business Presmises Levy\n1. Urban Registration\n2. Urban Renewal\n3. Rural registration\n4. Rural renewal"
    development_levy_options: "Pay Development Levy\n1. (Individuals only) not more than N100 per annum on all taxable individuals. Press 1 to continue"
    market_tax_options: "Pay Market Taxes and Levies:\nPress 1 to continue"
    local_govt_options: "Pay Local Govt. Taxes & Levies\n1. Shops & Kiosk\n2. Tenement rates\n3. Motor Park\n4. Wrong parking\n5.Signboard & Advertisement"
    land_use_options: "Pay Land Use Fees:\nRight of occupancy fees on lands owned by State Govt.\nPress 1 to continue"
    enter_tax_year: "Enter Tax Year: "
    lbl_tax_year: "Tax Year: "
    individual_options: "Pay Individual Tax\n1. Self Assessment\n2. PAYE"
    enter_bill_id: "Pay Other Taxes & Levies\nEnter Bill Number:"
    lbl_payer_id: "PayerID: "
    lbl_fullname: "Fullname: "
    lbl_last_payment: "Last payment: "
    lbl_clearance_issued: "Clearance Issued:"
    lbl_tmp_id: "Temporary PayerId:"
    lbl_payer_notfound: "PayerId not found"
    lbl_registration_title: "TaxPayer Registration"
    lbl_new_payer_created: "Registration updated successfully"
    invalid_request: "Invalid request"
    lbl_name: "Name:"
    lbl_estimated: "Est.:"
    lbl_gross: "Gross:N"
    lbl_takehome: "Take home/Mo:N"
    lbl_tax: "Tax:N"
    lbl_deductions: "Deductions:N"
    lbl_freepay: "Tax Free:N"
    lbl_pension: "Pension(%):"
    lbl_nhf: "N.H.F(%):"
    lbl_tax_rate: "Tax Rate(%):"
    enter_taxpayer_fullname: "Enter Full Name e.g Taiwo Musa Okoro"
    confirmed_registration: "Registration completed."
    blank: ""
    states: "1. Lagos\n2. Delta\n3. Ondo\n4. Akwa Ibom"
    tax_news: "Declare your assets...come clean under VAIDS. LIRS"
    broadcast:
        - Declare your assets...come clean under VAIDS. LIRS
        - You will be held accountable if you have any irregularities in your tax status
        - Start the process of rectifying your tax irregularities at LIRS today
        - It is a tax levied on all incomes of an individual in employment or business
        - The Personal Income Tax (Amendment) Act, 2011 combined with the provisions of S.3 (1)(b) and S.3(1)(b)(i)
        - You can officially obtain information on all taxes paid on your behalf through the Executive Chairman of LIRS